### ISSUE TITLE
Since 4.0.0 grunt-ts ignoring templated parameters in 'out' string

### ISSUE THREAD

**Issue by paulgambrell** [TypeStrong/grunt-ts#220]
Now getting this error:

Running "ts:build" (ts) task
Compiling...
Cleared fast compile cache for target: build
Fast compile will not work when --out is specified. Ignoring fast compilation
Using tsc v1.4.1
error TS6053: File '%>/<%=.ts' not found.
error TS6054: File '%>.js' must have extension '.ts' or '.d.ts'.
error TS6054: File 'pkg.company' must have extension '.ts' or '.d.ts'.
error TS6054: File 'pkg.name' must have extension '.ts' or '.d.ts'.

With the following call:

        ts: {
            build: {
                src: ['src/ts/**/*.ts'],
                reference: 'src/ref/Reference.ts',
                out: 'build/<%= pkg.company %>/<%= pkg.name %>.js',
                options: {
                    target: 'es5',
                    module: 'amd',
                    declaration: true,
                    sourceMap: true,
                    removeComments: true
                }
            }
        },

Whereas previously pkg.company and pkg.name variables are replaced. Rolling back to 3.0.0 fixes the issue.

**Comment by nycdotnet** [comment]
Thanks for the report.  Will investigate this evening.

**Comment by JoeFirebaugh** [comment]
I can confirm the same behavior, FWIW.  :)

**Comment by nycdotnet** [comment]
This should be fixed - please re-open if not.  Thank you for the report.  I added you both to the Change Log.

**Comment by paulgambrell** [comment]
Thanks, will try it out as soon as github recovers fully from their attack, still getting timeouts on bower runs here

**Comment by JoeFirebaugh** [comment]
I just tried it this morning, works fine again.  Thanks for a quick fix Steve!

**Comment by nycdotnet** [comment]
w00t.
