### ISSUE TITLE
Beta9 causes implicit compilation of node_modules

### ISSUE THREAD

**Issue by metamaker** [TypeStrong/grunt-ts#392]
Most of what is here is from some AngularJS2 boilerplate (not sure what exact boilerplate). I have next configuration in `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "spec",
    "e2e",
    "node_modules"
  ]
}
```
In `Gruntfile.js` I have next:

```javascript
// ... some code
    ts: {
            build: {
                src: ['app/**/*.ts', '!app/**/*.spec.ts', 'typings/**/*.ts', 'missing_typings/**/*.ts'],
                outDir: 'dist',
                tsconfig: 'tsconfig.json'
            },
            options: {
                fast: 'never',
                verbose: true
            }
        },
// ... moar code
```

I use `typings` package.

When running `grunt` with `grunt-ts-5.5.1` everything compiles fine, command for `tsc` is next:

[grunt-ts-5.5.1-cmd.txt](https://github.com/TypeStrong/grunt-ts/files/696289/grunt-ts-5.5.1-cmd.txt)

However, in `grunt-ts-6.0.0-beta.9` compilation fails. Command for `tsc` is different and doesn't notice that typings were specified in  `typings/` directory, and tries to compile `node_modules` directly. Specifying `!node_modules/**/*.ts` in `src` doesn't help.

[grunt-ts-6.0.0beta.9-cmd.txt](https://github.com/TypeStrong/grunt-ts/files/696290/grunt-ts-6.0.0beta.9-cmd.txt)

**Comment by nycdotnet** [comment]
Thanks for the report.  I'll take a look.

**Comment by nycdotnet** [comment]
Would you please try again with `grunt-ts@6.0.0-beta.10` which has just been published to npm.

**Comment by metamaker** [comment]
I changed my configuration a bit.

`tsconfig.json` is the same.
ts part in `Gruntfile.js` is next:

```javascript
      ts: {
            dev: {
                src: [
                    'app/**/*.ts',
                    '!app/**/*.spec.ts'
                ],
                outDir: 'dist/dev',
                tsconfig: 'tsconfig.json',
                baseDir: 'app',
                options: {
                    fast: 'always',
                    rootDir: 'app',
                    additionalFlags: 'missing-typings/missing.d.ts typings/index.d.ts' // Include typings during every compilation attempt
                }
            },
            prod: {
                src: '<%= ts.dev.src %>',
                out: 'dist/prod/index.min.js',
                tsconfig: 'tsconfig.json',
                baseDir: 'app',
                options: {
                    fast: 'never',
                    rootDir: 'app',
                }
            },
            "test-karma": {
                src: [
                    'app/**/*.ts', // Including .spec files
                ],
                outDir: 'dist/test/karma',
                tsconfig: 'tsconfig.json',
                baseDir: 'app',
                options: {
                    fast: 'always',
                    rootDir: 'app',
                    additionalFlags: 'missing-typings/missing.d.ts typings/index.d.ts' // Include typings during every compilation attempt
                }
            },
            "test-e2e": {
                src: [
                    '**/*e2e-spec.ts'
                ],
                outDir: 'dist/test/e2e/from-ts',
                baseDir: '.',
                options: {
                    fast: 'never',
                }
            }
        },
```

5.5.1 works
[5.5.1.txt](https://github.com/TypeStrong/grunt-ts/files/702410/5.5.1.txt)

6.0.0 still fails
[6.0.0-beta10.txt](https://github.com/TypeStrong/grunt-ts/files/702403/6.0.0-beta10.txt)

**Comment by nycdotnet** [comment]
Hi - I believe I figured out what's going on.  The negation globs from the gruntfile were not being considered when evaluating the implicit globs in the tsconfig.json file.  This should now be fixed in grunt-ts@6.0.0-beta.10 which I've just published to npm.  Would you please take a look?  Thank you for all the reports.  I will look into the fast thing soon.

**Comment by metamaker** [comment]
Yes, no problem I will have a look on Monday (I have to do it from my work PC, so can't do it earlier). Much thanks for your help with issues!

**Comment by metamaker** [comment]
Still same problem as in 6.0.0-beta.9 - it started including `node_modules` folder. Sadly, I can't share my source code for you to test as it is not my intellectual property.

**Comment by nycdotnet** [comment]
just to confirm- did you really retest with beta 9?  I don't think this issue was resolved until beta 10.

**Comment by metamaker** [comment]
> just to confirm- did you really retest with beta 9? I don't think this issue was resolved until beta 10.
I retested both beta9 and beta10, the problem still exists. I use nodejs 7.4.0, btw, maybe it is the reason, because it looks like node 7.4.0 creates additional `node_modules/@types` folder that contains typings. Sorry, I can't look into it deeper - too much other work these days :( .

**Comment by nycdotnet** [comment]
Thank you for all the help.  I'll keep investigating.

**Comment by xtazy** [comment]
Same problem for me, stuck in 6.0.0-beta.3

**Comment by nycdotnet** [comment]
I will spend some time on this today - thanks.

**Comment by nycdotnet** [comment]
Thanks @metamaker and @xtazy for reporting this issue.  I was able to resolve an issue earlier in this thread, but I'm not able to make further progress.  It seems to be working correctly on my end.

In order to make some progress, I've created a new Angular 2 project using their quickstart repo here: https://github.com/nycdotnet/grunt-ts-issue-392/

If you run the following you should be able to help troubleshoot:

```
git clone https://github.com/nycdotnet/grunt-ts-issue-392/
cd grunt-ts-issue-392
npm install
grunt
```

From the above, grunt-ts is going to only compile the .d.ts files that are referenced inside of the node_modules folder by the TypeScript source files.  If you uncomment the `tsconfig` line in the tsconfig.json file, it should be the same list of files to compile.  Are you seeing something different?  If not, what is different about this project versus your projects?

Thank you again for all of your help.

**Comment by nycdotnet** [comment]
@basarat Any chance you'd be willing to run v6.0.0-beta.10 through its paces?  I haven't been able to find any more issues.

**Comment by basarat** [comment]
@nycdotnet I don't use gulp or grunt in any of my currently active projects 😢 :rose:

**Comment by nycdotnet** [comment]
I believe this is resolved in the latest beta on npm.  Please re-open if not.  Thank you!
